//
// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
//


class Solution {
public:
    char findTheDifference(string s, string t) {
        int cnts[26] = {0};
        
        //hashmap
        for(char c : s) ++cnts[c-'a'];
        
        //find in t
        for(char c : t) {
            //cout<<c<<cnts[c-'a'];
            if(--cnts[c-'a'] < 0) return c;
        }
        char ans;
        return ans;
    }
};
